apiVersion: v1
kind: Service
metadata:
  name: nodejs-component-service  
spec:
  selector:
    app: nodejs-component
  ports:
    - port: 80
      targetPort: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-component
  labels:
    backstage.io/kubernetes-id: nodejs-component
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-component
  template:
    metadata:
      labels:
        app: nodejs-component
        backstage.io/kubernetes-id: nodejs-component
    spec:
      containers:
      - name: nodejs-component
        image: johnvoloski/nodejs-component
        imagePullPolicy: Always
        ports:
          - containerPort: 4000
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 128Mi